version: '3.9'

services:
#primer servicio 
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/keew_proyect
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    #links:
    #  - db
 # db:
 #   image: mongo:3.6.23
 #   ports:
 #     - 27017:27017